=== api-evangelist/new-relic/json-schema/new-relic-keytransactionresponsetype-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "#/components/schemas/KeyTransactionResponseType",
  "title": "KeyTransactionResponseType",
  "type": "object",
  "properties": {
    "application_summary": {
      "$ref": "#/components/schemas/AppSummaryResponse"
    },
    "end_user_summary": {
      "$ref": "#/components/schemas/EndUserSummaryResponse"
    },
    "health_status": {
      "type": "string",
      "example": "active"
    },
    "id": {
      "type": "integer",
      "example": 100
    },
    "last_reported_at": {
      "type": "string",
      "format": "date-time",
      "example": "2026-04-18T14:30:00Z"
    },
    "links": {
      "$ref": "#/components/schemas/KeyTransactionLinksResponse"
    },
    "name": {
      "type": "string",
      "example": "example-resource-01"
    },
    "reporting": {
      "type": "boolean",
      "example": true
    },
    "transaction_name": {
      "type": "string",
      "example": "example_string"
    }
  }
}

=== api-evangelist/new-relic/examples/new-relic-key-transaction-response-type-example.json
{
  "application_summary": {
    "apdex_score": 87.5,
    "apdex_target": 42.5,
    "concurrent_instance_count": 42,
    "error_rate": 12.3,
    "host_count": 42,
    "instance_count": 42,
    "response_time": 42.5,
    "throughput": 42.5
  },
  "end_user_summary": {
    "apdex_score": 87.5,
    "apdex_target": 42.5,
    "response_time": 42.5,
    "throughput": 42.5
  },
  "health_status": "active",
  "id": 100,
  "last_reported_at": "2026-04-18T14:30:00Z",
  "links": {
    "application": 100
  },
  "name": "example-resource-01",
  "reporting": true,
  "transaction_name": "example_string"
}
