=== api-evangelist/new-relic/json-schema/new-relic-mobileapplicationresponsetype-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "#/components/schemas/MobileApplicationResponseType",
  "title": "MobileApplicationResponseType",
  "type": "object",
  "properties": {
    "crash_summary": {
      "$ref": "#/components/schemas/CrashSummaryResponse"
    },
    "health_status": {
      "type": "string",
      "example": "active"
    },
    "id": {
      "type": "integer",
      "example": 100
    },
    "mobile_summary": {
      "$ref": "#/components/schemas/MobileSummaryDataResponse"
    },
    "name": {
      "type": "string",
      "example": "example-resource-01"
    },
    "reporting": {
      "type": "boolean",
      "example": true
    }
  }
}

=== api-evangelist/new-relic/examples/new-relic-mobile-application-response-type-example.json
{
  "crash_summary": {
    "crash_count": 42,
    "crash_rate": 12.3,
    "supports_crash_data": true,
    "unresolved_crash_count": 42
  },
  "health_status": "active",
  "id": 100,
  "mobile_summary": {
    "active_users": 100,
    "calls_per_session": 42.5,
    "failed_call_rate": 12.3,
    "interaction_time": 42.5,
    "launch_count": 42,
    "remote_error_rate": 12.3,
    "response_time": 42.5,
    "throughput": 42.5
  },
  "name": "example-resource-01",
  "reporting": true
}
