=== api-evangelist/new-relic/json-schema/new-relic-applicationresponsetype-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "#/components/schemas/ApplicationResponseType",
  "title": "ApplicationResponseType",
  "type": "object",
  "properties": {
    "application_summary": {
      "$ref": "#/components/schemas/AppSummaryResponse"
    },
    "end_user_summary": {
      "$ref": "#/components/schemas/EndUserSummaryResponse"
    },
    "health_status": {
      "type": "string",
      "example": "active"
    },
    "id": {
      "type": "integer",
      "example": 100
    },
    "language": {
      "type": "string",
      "example": "example_string"
    },
    "last_reported_at": {
      "type": "string",
      "format": "date-time",
      "example": "2026-04-18T14:30:00Z"
    },
    "links": {
      "$ref": "#/components/schemas/ApplicationLinksResponse"
    },
    "name": {
      "type": "string",
      "example": "example-resource-01"
    },
    "reporting": {
      "type": "boolean",
      "example": true
    },
    "settings": {
      "$ref": "#/components/schemas/AppSettingsResponse"
    }
  }
}

=== api-evangelist/new-relic/examples/new-relic-application-response-type-example.json
{
  "application_summary": {
    "apdex_score": 87.5,
    "apdex_target": 42.5,
    "concurrent_instance_count": 42,
    "error_rate": 12.3,
    "host_count": 42,
    "instance_count": 42,
    "response_time": 42.5,
    "throughput": 42.5
  },
  "end_user_summary": {
    "apdex_score": 87.5,
    "apdex_target": 42.5,
    "response_time": 42.5,
    "throughput": 42.5
  },
  "health_status": "active",
  "id": 100,
  "language": "example_string",
  "last_reported_at": "2026-04-18T14:30:00Z",
  "links": {
    "servers": [
      100
    ],
    "application_hosts": [
      100
    ],
    "application_instances": [
      100
    ]
  },
  "name": "example-resource-01",
  "reporting": true,
  "settings": {
    "app_apdex_threshold": 42.5,
    "enable_real_user_monitoring": true,
    "end_user_apdex_threshold": 42.5,
    "use_server_side_config": true
  }
}
